### PR TITLE
platform: nordic_nrf: Update nrfx to version 2.2.0

### PR DESCRIPTION
**Pull request by anangl**
Update nrfx to the recently released version. See
https://github.com/NordicSemiconductor/nrfx/blob/v2.2.0/CHANGELOG.md
for a list of changes that this version introduces.

Additionally, this update includes the hotfix for nrfx_spim from commit
59ad34410bf79b9b50b86c8befb9d71024f04c0b in the nrfx repository.

Note: this commit extends the scope of the import from nrfx to all
available drivers and all supported SoCs.

Origin: nrfx
License: BSD 3-Clause
URL: https://github.com/NordicSemiconductor/nrfx/tree/v2.2.0
commit: a5397bea558fb4b6838081a22d1ee679289d7417
Purpose: Provide peripheral drivers for Nordic SoCs
Maintained-by: External

Signed-off-by: Andrzej Głąbek <andrzej.glabek@nordicsemi.no>

### CODE REVIEW

**Comment by anangl** [comment]
Compared to what is imported to https://github.com/zephyrproject-rtos/hal_nordic, I skipped the files related to generation of documentation (directories `doc/` and `templates/`).
The question is if it is desirable to import `mdk/*.svd` files here. Those combined make ~16 MB.

**Review by oyvindronningstad — APPROVED** [review]

**Comment by ioannisg** [comment]
> The question is if it is desirable to import `mdk/*.svd` files here. Those combined make ~16 MB.

I don't believe so, would we use them?

**Comment by anangl** [comment]
> > The question is if it is desirable to import `mdk/*.svd` files here. Those combined make ~16 MB.
> 
> I don't believe so, would we use them?

They could help in debugging. That's why they are imported to hal_nordic. I will remove them from this PR. We can add them later if needed.

**Comment by anangl** [comment]
Removed `mdk/*.svd` files.

**Review by ioannisg — APPROVED** [review]

**Pull request merged**
